### ISSUE TITLE
Unable to install my package [2]

### ISSUE THREAD

**Issue by italomaia** [luarocks/luarocks#1017]
Following suggestion in https://github.com/luarocks/luarocks/issues/1010 I fixed the source url value. Now I get another error:

`Error: Expected filename in format 'name-version-revision.rockspec'.`

Rockspect file for https://github.com/italomaia/lua_fun seems to be following naming convetion alright: lua_fun-0.4-3.rockspec

**Comment by daurnimator** [comment]
Your rockspec works for me. How did you try to run it?

**Comment by italomaia** [comment]
```
~> luarocks install --local lua_fun
Installing https://luarocks.org/lua_fun-0.4.0.rockspec

Error: Expected filename in format 'name-version-revision.rockspec'.
~> # doesn't work
~> cd Projetos/lua_fun/
~/P/lua_fun> luarocks install --local lua_fun-0.4-3.rockspec 
~> # works
```

**Comment by siffiejoe** [comment]
It seems the rockspec with the invalid version (`0.4.0`, version number triple, no revision) takes precedence over the correct one (`0.4-3`, version number pair, with revision) in the luarocks repository. Since most likely no one was able to install the invalid rockspec, the easiest fix would be to remove the broken rockspec from the repository.

In the future we should reject invalid uploads to the repository and decide on the relative order of `0.4-1` vs. `0.4.x-1` (x >= 0).

**Comment by italomaia** [comment]
Thanks for the suggestion @siffiejoe Now it works. Why invalid rockspec files were accepted was another question of mine. Double thanks!
