### ISSUE TITLE
Error when trying to build mpack: fs.lua:79: cfg is not initialized, please run cfg.init() first

### ISSUE THREAD

**Issue by blueyed** [luarocks/luarocks#1069]
I am seeing the following error when trying to build mpack (using LuaRocks 3.2.0, via Neovims third-party build system, [full log](https://travis-ci.org/neovim/neovim/jobs/578102145#L1151)):

```
[48/81] Generating usr/lib/luarocks/rocks-5.1/mpack
FAILED: cd /home/travis/nvim-deps && /home/travis/nvim-deps/usr/bin/luarocks build mpack 1.0.8-0 CC=/usr/lib/ccache/gcc LD=/usr/lib/ccache/gcc
/home/travis/nvim-deps/usr/bin/luajit: /home/travis/nvim-deps/usr/share/lua/5.1/luarocks/fs.lua:79: cfg is not initialized, please run cfg.init() first
stack traceback:
	[C]: in function 'error'
	/home/travis/nvim-deps/usr/share/lua/5.1/luarocks/fs.lua:79: in function 'init'
	/home/travis/nvim-deps/usr/share/lua/5.1/luarocks/cmd.lua:447: in function 'run_command'
	...usr/lib/luarocks/rocks-5.1/luarocks/3.2.0-1/bin/luarocks:35: in main chunk
	[C]: at 0x00404560
```

(via https://github.com/neovim/neovim/pull/10292#issuecomment-525972116).

This worked when using Luarocks via a snapshot a while ago (1d3bb56), but also fails when re-trying it - so it might be related to other external updates.
The log from when it worked with 1d3bb56 (https://travis-ci.org/neovim/neovim/jobs/564563074):
```
[79/90] Performing install step for 'luarocks'[K
mkdir -p "build"
mkdir -p .luarocks
cp ./build/config-5.1.lua .luarocks/config-5.1.lua
rm -f src/luarocks/core/hardcoded.lua
echo "#!/bin/sh" > luarocks
echo "unset LUA_PATH LUA_PATH_5_2 LUA_PATH_5_3 LUA_PATH_5_4 LUA_CPATH LUA_CPATH_5_2 LUA_CPATH_5_3 LUA_CPATH_5_4" >> luarocks
echo 'LUAROCKS_SYSCONFDIR="/home/travis/nvim-deps/usr/etc/luarocks" LUA_PATH="/home/travis/nvim-deps/build/src/luarocks/src/?.lua;;" exec "/home/travis/nvim-deps/usr/bin/luajit" "/home/travis/nvim-deps/build/src/luarocks/src/bin/luarocks" --project-tree="/home/travis/nvim-deps/build/src/luarocks/lua_modules" "$@"' >> luarocks
chmod +rx ./luarocks
./luarocks init

Initializing project 'luarocks' for Lua 5.1 ...
-----------------------------------------------

Checking your Lua installation ...
Adding entries to .gitignore ...
Preparing ./.luarocks/ ...
Wrote .luarocks/config-5.1.lua
Preparing ./lua_modules/ ...
./luarocks already exists. Not overwriting it!
Preparing ./lua for version 5.1...
mkdir -p "/home/travis/nvim-deps/usr/etc/luarocks"
install -m 644 "build/config-5.1.lua" "/home/travis/nvim-deps/usr/etc/luarocks/config-5.1.lua"
./luarocks make --tree="/home/travis/nvim-deps/usr"

No existing manifest. Attempting to rebuild...
luarocks dev-1 is now installed in /home/travis/nvim-deps/usr (license: MIT)


[80/90] Completed 'luarocks'[K
[80/90] Completed 'luarocks'[K
[81/90] Generating usr/lib/luarocks/rocks-5.1/mpack[K
[81/90] Generating usr/lib/luarocks/rocks-5.1/mpack[K

/usr/lib/ccache/cc -O2 -fPIC -I/home/travis/nvim-deps/usr/include/luajit-2.0 -c lmpack.c -o lmpack.o
/usr/lib/ccache/cc -shared -o mpack.so lmpack.o
mpack 1.0.8-0 is now installed in /home/travis/nvim-deps/usr (license: MIT)
```

**Comment by vtahlani** [comment]
I am getting same error while running "luarocks install lua-resty-session or luarocks install lua-resty-openidc"

/usr/bin/lua5.3: /usr/local/share/lua/5.3/luarocks/fs.lua:79: cfg is not initialized, please run cfg.init() first
stack traceback:
	[C]: in function 'error'
	/usr/local/share/lua/5.3/luarocks/fs.lua:79: in function 'luarocks.fs.init'
	/usr/local/share/lua/5.3/luarocks/cmd.lua:447: in function 'luarocks.cmd.run_command'
	...cal/lib/luarocks/rocks-5.3/luarocks/3.2.0-1/bin/luarocks:35: in main chunk
	[C]: in ?

Can you please suggest what is missing? how to run cfg.int()?

**Comment by pauloue** [comment]
I get the same error when using luarocks installed with `luarocks install luarocks`, but not when using luarocks built from source. I moved `fs.init()` before the call to `init_config` in e92c37b6e3b30268033eaf2ad634998340c0fa3e, but cfg is also inited in `loader.lua`. Adding `cfg.init()` before `fs.init()` in `cmd.run_command` fixes it.

**Comment by hishamhm** [comment]
Yeah, that bit is very tricky and dependent on your system. I noticed the problem and struggled with that myself before pushing the release, but I thought that forcing a custom package loader to ensure that LuaRocks would "find itself" would fix it. (But apparently that had an unforeseen side-effect on external commands, which also share the `luarocks.` namespace, see #1070).

The chicken-and-egg situation arised like this:

* `fs.init` initializes the fs module with varying built-in features depending on what Lua modules you happen to have
* detecting what Lua modules you have depends on your package paths, which depends on your configuration
* the configuration is initialized by `cfg.init`
* the operation of `cfg.init` is affected by CLI flags (like `--project-tree`, `--lua-version`, etc.)

So the dependency order was: check CLI flags, `cfg.init`, then `fs.init`.

However, _after_ `fs.init` runs, we would load external commands in the `luarocks.cmd.external` namespace, using `fs.modules` to scan the filesystem. We did that late in the sequence because we only resolved subcommands as a final step.

But looks like @pauloue had to move loading the external modules way ahead, because it is needed by argparse to set everything up, before even handling CLI flags.

This shifted the dependency order to `fs.init`, then CLI flags, then `cfg.init`.

I added the package loader in e9215f139b to make the failing smoke-test work, and  assumed that my concern on only loading `fs.init` after a properly initialized `cfg.init` might have been overkill, if user's Lua paths were already set up via environment variables anyway (either by hand or via `luarocks path`).

This logic needs to be simplified, as I ended up with a spaghetti of interdependencies by trying to cater to a number of distinct scenarios all at the same time.

Perhaps a solution is to make it easy for the fs module to reconfigure itself after all CLI flags are loaded.

(As a side note, I'm not happy that we become sort of dependent on the "unconfigured" versions of luarocks.fs functions (which I would like to be able to eventually drop) just to run fs.modules in the external subcommand detection...)

**Comment by blueyed** [comment]
@hishamhm 
Any idea why it worked before with 1d3bb56 (v3.1.3-22-g1d3bb56), but not when trying it again?

**Comment by hishamhm** [comment]
@blueyed I don't know, it's very odd. I just tried to implement this:

> Perhaps a solution is to make it easy for the fs module to reconfigure itself after all CLI flags are loaded.

https://github.com/luarocks/luarocks/pull/1074

@blueyed Do have an easy way to give the above PR a try, to see if it helps?

**Comment by vtahlani** [comment]
Thanks all, if possible can you provide me commands which i need to execute to install it on ubanto?

**Comment by vtahlani** [comment]
@hishamhm I am getting below error when using commit 2de241f1010585af2528ef40ead82510afc44891

Step 11/46 : RUN luarocks install lua-resty-session
 ---> Running in a278296444af
/usr/bin/lua5.2: /usr/local/share/lua/5.2/luarocks/fs.lua:64: attempt to call field 'each_platform' (a nil value)
stack traceback:
	/usr/local/share/lua/5.2/luarocks/fs.lua:64: in function 'load_platform_fns'
	/usr/local/share/lua/5.2/luarocks/fs.lua:91: in function 'init'
	/usr/local/share/lua/5.2/luarocks/cmd.lua:447: in function 'run_command'
	...local/lib/luarocks/rocks-5.2/luarocks/dev-1/bin/luarocks:35: in main chunk
	[C]: in ?

**Comment by hishamhm** [comment]
@vtahlani Thanks for the feedback! How did you install LuaRocks? And could you try with db2b375 (PR #1083)?

**Comment by vtahlani** [comment]
I checked out the commit provided by you, executed configuration and then
ran make bootstrap

Git clone master
Git checkout <commit I'd provided by you>
. /configuration
Make bootstrap

Thanks
Veerbhan

**Comment by hishamhm** [comment]
@vtahlani are you getting the same problem with db2b375?

**Comment by hishamhm** [comment]
(@vtahlani in case you see this over email, I updated the question to point to the current master at c5ecbdf because PR #1083 has been merged)

**Comment by vtahlani** [comment]
@hishamhm [c5ecbdf](https://github.com/luarocks/luarocks/commit/c5ecbdfaffd96bb07928f63fbc0b7398333284b7) worked. Thanks for your help. Can you please suggest luarock authors to fix master/latest tag with your fixes?

Thanks a lot.

**Comment by hishamhm** [comment]
@vtahlani thank you for confirming! LuaRocks 3.2.1, containing those fixes, will be out shortly.
