### ISSUE TITLE
No luarocks.loader with Lua 5.1

### ISSUE THREAD

**Issue by gpanders** [luarocks/luarocks#1140]
Hi all.

Very new to Lua and completely new to Luarocks. I'm trying to install a project that uses Lua 5.1 and Luarocks to manage its dependencies. I'm on macOS with Homebrew. Here's what I've done so far:
```console
brew install lua
brew install lua@5.1
brew install luarocks
```
I can install the packages for Lua 5.1 using `luarocks`:
```console
luarocks --lua-dir=/usr/local/opt/lua5.1 --lua-version=5.1 luafilesystem
```
which installs the packages to my `~/.luarocks` directory. However, there is no `loader.lua` file under any 5.1 load path:
```console
$ find /usr/local -type f -name 'loader.lua'
/usr/local/Cellar/luarocks/3.2.1/share/lua/5.3/luarocks/loader.lua
```
As you can see, it's there for 5.3 but nothing for 5.1. So when I try to load `luarocks` from Lua 5.1, I get the following:
```lua
Lua 5.1.5  Copyright (C) 1994-2012 Lua.org, PUC-Rio
> require "luarocks.loader"
stdin:1: module 'luarocks.loader' not found:
        no field package.preload['luarocks.loader']
        no file './luarocks/loader.lua'
        no file '/usr/local/share/lua/5.1/luarocks/loader.lua'
        no file '/usr/local/share/lua/5.1/luarocks/loader/init.lua'
        no file '/usr/local/lib/lua/5.1/luarocks/loader.lua'
        no file '/usr/local/lib/lua/5.1/luarocks/loader/init.lua'
        no file './luarocks/loader.so'
        no file '/usr/local/lib/lua/5.1/luarocks/loader.so'
        no file '/usr/local/lib/lua/5.1/loadall.so'
        no file './luarocks.so'
        no file '/usr/local/lib/lua/5.1/luarocks.so'
        no file '/usr/local/lib/lua/5.1/loadall.so'
stack traceback:
        [C]: in function 'require'
        stdin:1: in main chunk
        [C]: ?
```

I've tried searching but haven't been able to come up with anything.

**Comment by hishamhm** [comment]
Looks like LuaRocks in Homebrew was built using Lua 5.3. While it can _manage_ Lua 5.1 packages, it does not ship with the files in place to use `luarocks.loader` on Lua 5.1 out of the box.

You could copy (or symbolic-link) all of `/usr/local/Cellar/luarocks/3.2.1/share/lua/5.3/` into `/usr/local/share/lua/5.1` and that would work (though possibly a little messy in your system)

Alternatively, if you run the following in your shell, it should set all environment variables so that Lua 5.1 finds the LuaRocks-installed modules without requiring `luarocks.loader`:

```
eval $(luarocks --lua-dir=/usr/local/opt/lua5.1 --lua-version=5.1 path)
```

(this only takes effect for the current-running shell, though)

As a side note: any particular reason why you are targeting Lua 5.1 specifically? I see you installed both `lua` (5.3) and `lua@5.1`.

**Comment by gpanders** [comment]
> Alternatively, if you run the following in your shell, it should set all environment variables so that Lua 5.1 finds the LuaRocks-installed modules without requiring `luarocks.loader`

I did try this, but the script I'm using `require`s `luarocks.loader` explicitly, so it still ran into this error.

> As a side note: any particular reason why you are targeting Lua 5.1 specifically? I see you installed both `lua` (5.3) and `lua@5.1`.
I'm installing a 3rd party tool that uses 5.1. I tried running it with just `lua` but that gave all kinds of different errors.

FWIW I installed LuaRocks from source for Lua 5.1 and everything worked, so this is just a problem with the Homebrew installation I guess.
