### ISSUE TITLE
luarocks init wrapper conflicts with use cases that need the -e flag

### ISSUE THREAD

**Issue by andrewstarks** [luarocks/luarocks#1249]
Currently, the lua wrapper uses the `-e` flag to reset `package.path` and `package.cpath`, which works fine. However, ZeroBraneStudio also uses the `-e` flag, which means that the shell script does not work as expected. 

A solution is to use environment variables instead of changing the path in Lua. An example script, which works with ZBS:

```sh
#!/bin/sh

LUA_PATH_5_4="$PWD/lua_modules/share/lua/5.4/?.lua;$PWD/lua_modules/share/lua/5.4/?/init.lua;$PWD/src/?.lua;$PWD/src/?/init.lua;" LUA_CPATH_5_4="$PWD/lua_modules/lib/lua/5.4/?.so;" LUAROCKS_SYSCONFDIR='/usr/local/etc/luarocks' exec '/usr/local/bin/lua'  $([ "$*" ] || echo -i) "$@"
```

**Comment by hishamhm** [comment]
Oh boy. Unfortunately there's no way to make everyone happy. :(

In the beginning of times, we *did* use environment variables, just like you suggested. The oldest commit in the LuaRocks git tree, from 2009, (which is a port from the last state in CVS), contains this: a88d6f2eeba2b3355c33fac6d736cf6086342f47

Then in 2013, we switched to `-e`, because people complained that environment variables messed up with subprocesses: 504f70f3b7724d8449be76a06dba13f22a1b73f4

Then in 2018, we changed it back to an environment variable again (this time `LUA_INIT`), for reasons I don't exactly recall: 9941d6d52c1052d449aec6b77adf95f2d308e320

Then in 2019, we reverted it back to `-e`, because of #980: bb88566e070d3b69d87c345ba9118401c195a7ee

Honestly at this point I don't know what to do.

**Comment by andrewstarks** [comment]
Ha! I feel your pain and I thank you for being so patient with the public.

I double-checked, and it turns out that this is not really an issue. You can have two `-e` flags. I was fighting several issues and I had thought that using the above form solved the problem, but upon further review, it did not.

It works well as is. Thanks for responding so quickly and apologies for the noise.
