### ISSUE TITLE
cmake build: No rule to make target 'install'

### ISSUE THREAD

**Issue by meandmymind** [luarocks/luarocks#1286]
I use lua project with cpp library and build it with cmake by `luarocks make`

cmake installation goes well
```
Scanning dependencies of target xxx
[ 33%] Building CXX object CMakeFiles/xxx.dir/src/xxx.cc.o
[ 66%] Building CXX object CMakeFiles/xxx.dir/src/xxx.cc.o
[100%] Linking CXX shared library xxx.so
[100%] Built target xxx
```

and then I get error `make: *** No rule to make target 'install'.  Stop.`

generated Makefile in fact does not contain target `install`

how is it possible?

relevant rockspec 
```
build = {
    type= "cmake",
    install = {
        lib = {
            "./build.luarocks/xxx.so",
             ["xxx"]="./xxx/xxx",
             ["xxx"]="./xxx/xxx",
             ["xxx"]="./xxx/xxx",
             ["xxx"]="./xxx/xxx"
        }
    }
}
```

Furthermore, I build my project in docker container, and when I run this same code with same docker image in GitLab CI target `install` is found normally. 

LuaRocks version 3.0.3

**Comment by hishamhm** [comment]
@meandmymind If you want to disable the `cmake --target install` step, add `build.install_pass = false` to your rockspec (since you're doing `build.install.lib` explicitly, that should fix your problem, I believe).

But the fact that it's working in your CI environment but not in your Docker environment seems to indicate you have some other issue with your CMake installation that's outside of LuaRocks -- sorry, can't help you there!

**Comment by meandmymind** [comment]
@hishamhm, Yeah it was issue with CMake: I had wrond version of cpp dependency, so it caused build to fail.

But the main issue is still there -- fail was **silent** and no logs from cmake were given to me. Can we improve UX here by providing error logs of cmake?
