### ISSUE TITLE
Luarocks timeouts pulling packages?

### ISSUE THREAD

**Issue by jeremyjpj0916** [luarocks/luarocks#1299]
Having some of my pipeline builds failing recently trying to pull down my luarocks packages:

![image](https://user-images.githubusercontent.com/31913027/114511734-4c5f8f80-9c06-11eb-9278-b7812bab1ce6.png)

Was testing via curl just doing ```curl -k https://luarocks.org/kong-splunk-log-0.3-3.src.rock -vv``` , it succeeded about 2 times then failed the 3rd time with a hanging timeout. Server stressed atm? 

```
➜  ~ curl -k https://luarocks.org/kong-splunk-log-0.3-3.src.rock -vv
*   Trying 45.33.61.132...
* TCP_NODELAY set
* Connected to luarocks.org (45.33.61.132) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/cert.pem
  CApath: none
* TLSv1.2 (OUT), TLS handshake, Client hello (1):
* TLSv1.2 (IN), TLS handshake, Server hello (2):
* TLSv1.2 (IN), TLS handshake, Certificate (11):
* TLSv1.2 (IN), TLS handshake, Server key exchange (12):
* TLSv1.2 (IN), TLS handshake, Server finished (14):
* TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
* TLSv1.2 (OUT), TLS change cipher, Change cipher spec (1):
* TLSv1.2 (OUT), TLS handshake, Finished (20):
* TLSv1.2 (IN), TLS change cipher, Change cipher spec (1):
* TLSv1.2 (IN), TLS handshake, Finished (20):
* SSL connection using TLSv1.2 / ECDHE-RSA-AES256-GCM-SHA384
* ALPN, server accepted to use http/1.1
* Server certificate:
*  subject: CN=luarocks.org
*  start date: Mar 21 23:11:37 2021 GMT
*  expire date: Jun 19 23:11:37 2021 GMT
*  issuer: C=US; O=Let's Encrypt; CN=R3
*  SSL certificate verify ok.
> GET /kong-splunk-log-0.3-3.src.rock HTTP/1.1
> Host: luarocks.org
> User-Agent: curl/7.64.1
> Accept: */*
>
< HTTP/1.1 504 Gateway Time-out
< Server: nginx/1.18.0
< Date: Tue, 13 Apr 2021 07:09:49 GMT
< Content-Type: text/html
< Content-Length: 167
< Connection: keep-alive
<
<html>
<head><title>504 Gateway Time-out</title></head>
<body>
<center><h1>504 Gateway Time-out</h1></center>
<hr><center>nginx/1.18.0</center>
</body>
</html>
* Connection #0 to host luarocks.org left intact
* Closing connection 0
```

Usually luarocks org has been stable like a tank. This is new to me.

**Comment by jeremyjpj0916** [comment]
Added here too: https://github.com/luarocks/luarocks-site/issues/174 , wasn't sure which location is more relevant for this issue, feel free to close 1 or the other so we keep the right one in the right place.

**Comment by hishamhm** [comment]
I replied at the luarocks-site comment, but another question that's worth tracking here is why did the LuaRocks CLI fail, since its default configuration also has a fallback for a Github mirror. If I change my config to point to an invalid domain instead of luarocks.org, it falls back to Github correctly and then succeeds. If the CLI is not falling back upon getting a 504 from the main site, then that's something separate from the server issue, that we need to track here.

**Comment by jeremyjpj0916** [comment]
Sure, yes our pipelined CLI failed out too, the curl commands was just me manually proving it. Some output from our jenkins pipeline like so too:
```
Removing intermediate container 0f0f2f685cc1
 ---> e7e4ecfb96d5
Step 32/66 : RUN luarocks install kong-splunk-log
 ---> Running in d3416851fe5b
Installing https://luarocks.org/kong-splunk-log-0.3-3.src.rock

Error: Could not fetch rock file: Error fetching file: Failed downloading https://luarocks.org/kong-splunk-log-0.3-3.src.rock - kong-splunk-log-0.3-3.src.rock
The command '/bin/sh -c luarocks install kong-splunk-log' returned a non-zero code: 1
[Pipeline] echo
```

We didn't configure anything special to change a fallback behavior either that I know of in our env, everything should be vanilla.

**Comment by hishamhm** [comment]
Ok, I've confirmed that the current behavior is the following: it's only checking whether to use a mirror in the first operation, when it fetches the manifest. If the manifest fails to load, it switches to the mirror and everything works from there. But if the manifest fetches ok and the then actual rock download fails with a 504, it gives up, instead of trying that in a mirror as well. Changing that to make it retry on a mirror should make it much more resilient.

Btw, https://raw.githubusercontent.com/rocks-moonscript-org/moonrocks-mirror/master/ is configured as a default mirror (which is updated daily). In particular, any command using that as a `--server`, such as `luarocks install luasocket --server=https://raw.githubusercontent.com/rocks-moonscript-org/moonrocks-mirror/master/` will skip straight to it and bypass luarocks.org.

**Comment by hishamhm** [comment]
Merged the behavior change in mirroring! I'll proceed to push a new release 3.7.0 containing it.

**Comment by jeremyjpj0916** [comment]
You tha man! Thanks again.
