### ISSUE TITLE
Luarocks not working with Lua 5.4.3

### ISSUE THREAD

**Issue by agraef** [luarocks/luarocks#1309]
This is *not* a duplicate of #1060, the error is different. I'm running Luarocks 3.7.0 using Lua 5.4.3 (both installed from the standard package repositories) on Manjaro (Arch). Whenever I try to install any package, I get the following error message and backtrace:

~~~
Error: LuaRocks 3.7.0 bug (please report at https://github.com/luarocks/luarocks/issues).
Arch.: linux-x86_64
/usr/share/lua/5.4/ssl/https.lua:66: bad argument #2 to 'method' (string expected, got light userdata)
stack traceback:
        [C]: in function 'socket.http.request'
        /usr/share/lua/5.4/ssl/https.lua:132: in function 'ssl.https.request'
        /usr/share/lua/5.4/luarocks/fs/lua.lua:729: in upvalue 'request'
        /usr/share/lua/5.4/luarocks/fs/lua.lua:837: in upvalue 'http_request'
        /usr/share/lua/5.4/luarocks/fs/lua.lua:904: in function 'luarocks.fs.lua.download'
        (...tail calls...)
        /usr/share/lua/5.4/luarocks/fetch.lua:154: in function 'luarocks.fetch.fetch_url'
        /usr/share/lua/5.4/luarocks/fetch.lua:50: in function 'luarocks.fetch.fetch_caching'
        /usr/share/lua/5.4/luarocks/manif.lua:108: in function 'luarocks.manif.load_manifest'
        /usr/share/lua/5.4/luarocks/search.lua:111: in function </usr/share/lua/5.4/luarocks/search.lua:101>
        (...tail calls...)
        /usr/share/lua/5.4/luarocks/search.lua:155: in function 'luarocks.search.search_repos'
        /usr/share/lua/5.4/luarocks/search.lua:241: in function 'luarocks.search.find_suitable_rock'
        /usr/share/lua/5.4/luarocks/search.lua:263: in function 'luarocks.search.find_rock_checking_lua_versions'
        /usr/share/lua/5.4/luarocks/cmd/install.lua:242: in function 'luarocks.cmd.install.command'
        (...tail calls...)
        [C]: in function 'xpcall'
        /usr/share/lua/5.4/luarocks/cmd.lua:663: in function 'luarocks.cmd.run_command'
        /usr/bin/luarocks:38: in main chunk
        [C]: in ?
~~~

Luarocks works fine if I run it with Lua 5.3, so apparently there's another incompatibility with the latest Lua version. Thanks in advance for looking into this. :)

**Comment by hishamhm** [comment]
Thank you for the report!

Two questions:
* How was LuaSec installed, via LuaRocks or via the system's package manager?
* Which version of LuaSec is installed for Lua 5.4?

**Comment by agraef** [comment]
Hmm, it's 0.9, from this package here: https://archlinux.org/packages/community/x86_64/lua-sec/

I see that a newer version is out upstream, so let me quickly check whether installing lua-sec from git fixes the issue.

**Comment by agraef** [comment]
Yep, updating lua-sec to the latest from git fixes the issue, so the issue is with Arch (outdated package). I will report it there. Thanks for the quick feedback!

**Comment by mblayman** [comment]
Hi, interesting issue here. I've been staring at the exact same traceback (with slight path variations) this evening while trying to build a new Lua buildpack for Heroku. The Heroku stack that I'm running is based on Ubuntu 22.04 which has a newer version of lua-sec than whatever would have been available at the time of this issue's discussion.

Looking a little closer at the traceback, I think the likely problem is with lua-socket, which seems to be calling `https.lua` from C with the wrong arguments. The Arch changelog for lua-socket suggests that Arch updated to a more modern version  around this time which I suspect fixed the invocation problem. Although, I suppose an older version of lua-sec that was in Arch at the time could be a contributor too. Maybe the newer version of lua-sec needed the newer version of lua-socket and that resolved the problem because the transitive dependency fixed things.

Ubuntu is running a version of lua-socket with a pre-3.0 release tag from 2016 (https://packages.ubuntu.com/jammy/lua-socket, https://github.com/lunarmodules/luasocket/commit/ac3201d62024b397e8d6e3376822176d681811ec).

Since I have no idea when lua-socket is going to be updated to something more recent, I guess I'm going to try compiling it from source in my buildpack to see if that will fix the issue. I'll try to report back if I'm successful as it might help with other Lua issues in the Debian Linux world.

**Comment by alerque** [comment]
I'm both the release manager for luasocket right now and the Arch Linux packager for it. If there is a problem upstream on the luasocket side I'd be happy to look into it, but it doesn't sound like that's the case. I can't do much about the Ubuntu builds using 6 year old releases.
