### ISSUE TITLE
core dumped installing luarocks

### ISSUE THREAD

**Issue by raulcejas04** [luarocks/luarocks#1366]
Platform: docker, ubuntu 20, virtual machine

I got "core dumped" when I run luarocks after install with apk add without any error.

This is the output when I install:
/ # apk add luarocks
(1/2) Installing curl (7.79.1-r0)
(2/2) Installing luarocks (2.4.4-r1)
Executing busybox-1.31.1-r9.trigger
OK: 67 MiB in 38 packages
/ # luarocks
Illegal instruction (core dumped)

This is my Dockerfile but I build it manually step by step.

This is my Dockerfile:
FROM kong:2.0.4-alpine
LABEL description="Alpine + Kong 2.0.4 + kong-oidc plugin"
USER root
RUN apk update && apk add git unzip luarocks
RUN luarocks install --pin lua-resty-jwt 0.2.2-0
RUN luarocks install kong-oidc
USER kong

Thank you.

**Comment by hishamhm** [comment]
This is a build issue with the binaries in your image, not with LuaRocks (which ships as pure Lua code). If this is on ARM, in particular, there have been issues with Alpine+ARM containers running LuaJIT before, which is the interpreter Kong uses. I believe this has been fixed in more recent Kong versions by patching LuaJIT, so you should try upgrading to a more recent image. In any case, if the issue persists, I recommend you contacting Kong support, since the Lua code in LuaRocks by itself shouldn't be able to produce "illegal instructions" as it does not operate at a native-code level. Hope this helps!

**Comment by raulcejas04** [comment]
Hello. My problem was about kong. It need sse4_2. I moved my container into a new server and now it works fine. Thank you.
