### ISSUE TITLE
lua-espeak is not availiable for any lua versions

### ISSUE THREAD

**Issue by chrpsh** [luarocks/luarocks#1386]
hello
i tried `$ luarocks install lua-espeak`, got error 
```
No results matching query were found for Lua 5.4.
To check if it is available for other Lua versions, use --check-lua-versions.
```

checked versions, and

```
$ luarocks install --check-lua-versions lua-speak
lua-speak not found for Lua 5.4.
Checking if available for other Lua versions...
Checking for Lua 5.1...
Checking for Lua 5.2...
Checking for Lua 5.3...

Error: No results matching query were found for Lua 5.4.
lua-speak is not available for any Lua versions.
```

is lua-speak is no longer supported? (luaforge also isn't available)
i know it's kinda old thing, but is there any chance to use it?

**Comment by hishamhm** [comment]
(Transferred the issue from the website repo to the CLI repo)

You made a typo there, you wrote `lua-speak` instead of `lua-espeak`.

lua-espeak does show up in the repository: https://luarocks.org/modules/luarocks/lua-espeak/1.36r1-1

It is a very old package and its owner hasn't claimed it since we transferred the luarocks server to its new luarocks.org infrastructure many years ago, so there's no real guarantee that it will work with the latest Lua 5.4 release, but if you want to access its source code, luarocks.org keeps a copy of it in the form of the .src.rock package (which you can extract with the `luarocks upload` command), even though LuaForge no longer exists.

Hope that helps!

**Comment by chrpsh** [comment]
thank you for the answer

i tried again and have different error:

```
Installing https://luarocks.org/lua-espeak-1.36r1-1.src.rock

Error: Could not find header file for ESPEAK
  No file espeak/speak_lib.h in /usr/local/include
  No file espeak/speak_lib.h in /usr/include
  No file espeak/speak_lib.h in /include
You may have to install ESPEAK in your system and/or pass ESPEAK_DIR or ESPEAK_INCDIR to the luarocks command.
Example: luarocks install lua-espeak ESPEAK_DIR=/usr/local
```

i downloaded src.rock package and `unpack` and then `build` but it's the same error, maybe something's wrong with package or is it something on my end?

**Comment by hishamhm** [comment]
@chrpsh Looks like it is not compatible with Lua 5.4? You might need to use Lua 5.1, or maybe contact the library author to see if there's an updated version.
