### ISSUE TITLE
Install error: callable.c:1237:38: error: too few arguments to function call, expected 4, have 3

### ISSUE THREAD

**Issue by willbprog127** [luarocks/luarocks#1486]
- **Platform:**
  - macOS 12.6.3 Monterey - Intel

- **LuaRocks version:**
  - /usr/local/bin/luarocks 3.9.1

- **Configuration file:**
  - Default configuration _(no config created or edited)_

- **LuaRocks output from when the issue occurred:**
```
fs.execute("make ", "LIBFLAG=-bundle -undefined dynamic_lookup -all_load", "PREFIX=/usr/local/lib/luarocks/rocks-5.4/lgi/0.9.2-1", "LUA_LIBDIR=/usr/local/lib/luarocks/rocks-5.4/lgi/0.9.2-1/lib", "LUA_CFLAGS=-O2 -fPIC -I/usr/local/opt/lua/include/lua5.4", "LUA_SHAREDIR=/usr/local/lib/luarocks/rocks-5.4/lgi/0.9.2-1/lua", "CC=env MACOSX_DEPLOYMENT_TARGET=11.0 gcc")
fs.Q("LIBFLAG=-bundle -undefined dynamic_lookup -all_load")
fs.Q("PREFIX=/usr/local/lib/luarocks/rocks-5.4/lgi/0.9.2-1")
fs.Q("LUA_LIBDIR=/usr/local/lib/luarocks/rocks-5.4/lgi/0.9.2-1/lib")
fs.Q("LUA_CFLAGS=-O2 -fPIC -I/usr/local/opt/lua/include/lua5.4")
fs.Q("LUA_SHAREDIR=/usr/local/lib/luarocks/rocks-5.4/lgi/0.9.2-1/lua")
fs.Q("CC=env MACOSX_DEPLOYMENT_TARGET=11.0 gcc")
fs.execute_string("make  'LIBFLAG=-bundle -undefined dynamic_lookup -all_load' 'PREFIX=/usr/local/lib/luarocks/rocks-5.4/lgi/0.9.2-1' 'LUA_LIBDIR=/usr/local/lib/luarocks/rocks-5.4/lgi/0.9.2-1/lib' 'LUA_CFLAGS=-O2 -fPIC -I/usr/local/opt/lua/include/lua5.4' 'LUA_SHAREDIR=/usr/local/lib/luarocks/rocks-5.4/lgi/0.9.2-1/lua' 'CC=env MACOSX_DEPLOYMENT_TARGET=11.0 gcc'")
fs.current_dir()
fs.absolute_name("/var/folders/x4/6vgrx37d3z9d3txb2vkfvnc40000gn/T//luarocks_lgi-0.9.2-1-mC5Iel", "/Users/will/Projects/lua/GtkButton")
fs.absolute_name("lgi", "/var/folders/x4/6vgrx37d3z9d3txb2vkfvnc40000gn/T//luarocks_lgi-0.9.2-1-mC5Iel")
fs.command_at("/var/folders/x4/6vgrx37d3z9d3txb2vkfvnc40000gn/T//luarocks_lgi-0.9.2-1-mC5Iel/lgi", "make  'LIBFLAG=-bundle -undefined dynamic_lookup -all_load' 'PREFIX=/usr/local/lib/luarocks/rocks-5.4/lgi/0.9.2-1' 'LUA_LIBDIR=/usr/local/lib/luarocks/rocks-5.4/lgi/0.9.2-1/lib' 'LUA_CFLAGS=-O2 -fPIC -I/usr/local/opt/lua/include/lua5.4' 'LUA_SHAREDIR=/usr/local/lib/luarocks/rocks-5.4/lgi/0.9.2-1/lua' 'CC=env MACOSX_DEPLOYMENT_TARGET=11.0 gcc'")
fs.absolute_name("/var/folders/x4/6vgrx37d3z9d3txb2vkfvnc40000gn/T//luarocks_lgi-0.9.2-1-mC5Iel/lgi")
fs.current_dir()
fs.absolute_name("/var/folders/x4/6vgrx37d3z9d3txb2vkfvnc40000gn/T//luarocks_lgi-0.9.2-1-mC5Iel", "/Users/will/Projects/lua/GtkButton")
fs.absolute_name("lgi", "/var/folders/x4/6vgrx37d3z9d3txb2vkfvnc40000gn/T//luarocks_lgi-0.9.2-1-mC5Iel")
fs.Q("/var/folders/x4/6vgrx37d3z9d3txb2vkfvnc40000gn/T//luarocks_lgi-0.9.2-1-mC5Iel/lgi")

os.execute: 	cd '/var/folders/x4/6vgrx37d3z9d3txb2vkfvnc40000gn/T//luarocks_lgi-0.9.2-1-mC5Iel/lgi' && make  'LIBFLAG=-bundle -undefined dynamic_lookup -all_load' 'PREFIX=/usr/local/lib/luarocks/rocks-5.4/lgi/0.9.2-1' 'LUA_LIBDIR=/usr/local/lib/luarocks/rocks-5.4/lgi/0.9.2-1/lib' 'LUA_CFLAGS=-O2 -fPIC -I/usr/local/opt/lua/include/lua5.4' 'LUA_SHAREDIR=/usr/local/lib/luarocks/rocks-5.4/lgi/0.9.2-1/lua' 'CC=env MACOSX_DEPLOYMENT_TARGET=11.0 gcc'
/Library/Developer/CommandLineTools/usr/bin/make -C lgi
pkg-config --exists 'gobject-introspection-1.0 >= 0.10.8' --print-errors
touch .depcheck
env MACOSX_DEPLOYMENT_TARGET=11.0 gcc -fno-common  -O2 -fPIC -I/usr/local/opt/lua/include/lua5.4 -I/usr/local/Cellar/gobject-introspection/1.74.0/include/gobject-introspection-1.0 -I/usr/local/Cellar/glib/2.74.5/include -I/usr/local/Cellar/glib/2.74.5/include/glib-2.0 -I/usr/local/Cellar/glib/2.74.5/lib/glib-2.0/include -I/usr/local/opt/gettext/include -I/usr/local/Cellar/pcre2/10.42/include -I/Library/Developer/CommandLineTools/SDKs/MacOSX12.sdk/usr/include/ffi -Wall -Wextra -O2 -g -DGOBJECT_INTROSPECTION_LIBDIR=\"/usr/local/Cellar/gobject-introspection/1.74.0/lib\" -c -o buffer.o buffer.c
env MACOSX_DEPLOYMENT_TARGET=11.0 gcc -fno-common  -O2 -fPIC -I/usr/local/opt/lua/include/lua5.4 -I/usr/local/Cellar/gobject-introspection/1.74.0/include/gobject-introspection-1.0 -I/usr/local/Cellar/glib/2.74.5/include -I/usr/local/Cellar/glib/2.74.5/include/glib-2.0 -I/usr/local/Cellar/glib/2.74.5/lib/glib-2.0/include -I/usr/local/opt/gettext/include -I/usr/local/Cellar/pcre2/10.42/include -I/Library/Developer/CommandLineTools/SDKs/MacOSX12.sdk/usr/include/ffi -Wall -Wextra -O2 -g -DGOBJECT_INTROSPECTION_LIBDIR=\"/usr/local/Cellar/gobject-introspection/1.74.0/lib\" -c -o callable.o callable.c
callable.c:1237:38: error: too few arguments to function call, expected 4, have 3
      res = lua_resume (L, NULL, npos);
            ~~~~~~~~~~               ^
/usr/local/opt/lua/include/lua5.4/lua.h:300:15: note: 'lua_resume' declared here
LUA_API int  (lua_resume)     (lua_State *L, lua_State *from, int narg,
              ^
1 error generated.
make[1]: *** [callable.o] Error 1
make: *** [all] Error 2
Results: 3
  1 (nil): nil
  2 (string): exit
  3 (number): 2
fs.pop_dir()

Error: Build error: Failed building.
```

- **Description:**
  - `lua` and `luarocks` were installed using Homebrew 3.6.20 on macOS Monterey (Intel)
  - Launched `Terminal`
  - Executed `luarocks install lgi`
  - Error occurred as shown

**Comment by siffiejoe** [comment]
Strictly speaking this is not a LuaRocks issue. The rock lgi just wasn't updated to Lua 5.4 yet (`lua_resume` in Lua 5.3 had three parameters, in Lua 5.4 it now has four). The `README.md` over at the [lgi github repository][1] states that Lua 5.4 support is experimental (and apparently not released yet), so you probably need to install the dev/scm version. Try `luarocks install https://raw.githubusercontent.com/lgi-devs/lgi/master/lgi-scm-1.rockspec`.

  [1]: https://github.com/lgi-devs/lgi

However, I feel like the LuaRocks repository is full of quick'n'dirty wrapper modules that become unmaintained the moment they are uploaded. The decision to encourage open-ended Lua version requirements (`lua >= 5.1` instead of `lua >= 5.1, < 5.4`) leads to a very low signal-to-noise ratio in the repository -- especially for binary modules.

There are many ways to make the Lua repository more useful for users again:
* start enforcing closed Lua version requirements on the luarocks-site
* mark modules with open-ended Lua version requirements compatible only with the minimum version unless
  - the latest module release date is after the newer Lua release dates
  - there is at least one uploaded binary rock for the newer Lua releases (this might need some long-discussed changes to binary rocks)
* give luarocks-site users (other than the maintainer) a way to mark the module incompatible with certain Lua versions to warn others
* ... more ideas? @luarocks/team-luarocks

**Comment by willbprog127** [comment]
@siffiejoe Thanks for the information! 👍 Indeed the install proceeded with the command you provided, unfortunately it looks like there's something wrong with `lgi` itself as the Lua program I'm trying to run is erroring.

I am only in an exploratory phase of Lua right now, so much of what you're speaking about is new to me.  Maybe Lua isn't the right tool for me after all?  Thanks again! 😄

**Comment by daurnimator** [comment]
> ... more ideas? @luarocks/team-luarocks

  - The majority of pure-lua scripts are going to be compatible across versions.
  - People rarely go back and update rockspecs for old releases

These two points make me thing that open ended versions (at least for pure-lua scripts) are a good thing.

**Comment by hishamhm** [comment]
Both open-ended and closed-ended versions have pros and cons. Over the years I've seen people complaining about both in equal measure:

* "This says it's compatible with `lua >= 5.1`, but it's not working with Lua 5.3!"
* "I know this code is compatible with Lua 5.4, but the rockspec refuses to install!"

>    the latest module release date is after the newer Lua release dates

Maybe we could use this heuristic in an advisory manner. If the Lua version is open-ended, and the rockspec is older than the Lua release, and it failed to build, we could provide a warning in the end saying: `This rockspec was not tested for this Lua release. You may want to contact the maintainers of this package.`

Conversely, if the Lua version is close-ended and it rejects to install due to the upper limit being lower than the latest version, we could provide a flag to bypass the Lua version check and provide a message saying: `This rockspec was not tested for this Lua release. You may want to try it anyway using --skip-lua-version-check and contact the maintainers of this package.`
