### ISSUE TITLE
`luarocks remove` does not work with `make` backend

### ISSUE THREAD

**Issue by berwynhoyt** [luarocks/luarocks#1516]
- **Platform:**
  - Linux (and probably others)

- **LuaRocks version:**
  - 3.9.2

- **Configuration file:**
  - default

- **Description:**
Even if the makefile has a `remove` target, `luarocks remove` does not invoke it. This means that when you `luarocks remove` a module that was installed with the `make` back-end, not everything is removed. It needs to be possible to specify `build.remove_target='remove'` in the rockspec.

For example, `luarocks install mlua` installs file `/usr/local/lib/yottadb/r138/plugin/mlua.xc` and `make remove` removes it, but `luarocks remove mlua` does not remove it.

Steps to reproduce:
  - Install [yottadb](https://yottadb.com/product/get-started/)    # (Prerequisite for mlua)
  - Install mlua:
```
sudo luarocks install mlua
sudo luarocks remove mlua
```

- **LuaRocks output from when the issue occurred:**
```
$ sudo luarocks remove mlua
Checking stability of dependencies in the absence of
mlua 0.3-1...

Removing mlua 0.3-1...
Removal successful.
```
Appears to work, but doesn't remove the same files that `luarock install` installed.

**Comment by daurnimator** [comment]
The build phase is different to the packaging phase: the makefile only exists at the `luarocks make` stage, not during installation/unpacking. luarocks keeps track of the files it installs in a `manifest` file in the rocks folder, a `luarocks remove` only removes what is written down in that manifest.

**Comment by berwynhoyt** [comment]
Hmmm... I see what you are saying.

Can you help me understand what is the right way to generate a manifest file that tracks the files that `make install` installs when using the `make` backend?

I've been trawling through the luarocks docs and haven't managed to figure this out.

**Comment by daurnimator** [comment]
Looks like you can't: luarocks will only just delete the files explicitly mentioned, plus the folder: https://github.com/luarocks/luarocks/blob/bb9d7ed38a092dde2b27e2adc7b386272f2890ee/src/luarocks/repos.lua#L684

**Comment by berwynhoyt** [comment]
It seems like it would be best if I could specify a luarock-install target in my Makefile, which could add to the Manifest the files it had installed. To do so, the Makefile would have to know where the manifest is located and then add to it. Would this seem like a good solution to you, or am I missing something?

To be honest, I'm a bit stymied because I can't seem to match the actual content of my manifest files with the [manifest file spec](https://github.com/luarocks/luarocks/wiki/Manifest-file-format) which says it requires 3 mandatory items 'repository', 'modules', 'commands', and optional 'dependencies'. But I see none of these in my manifest which looks like this:

```
rock_manifest = {
   ["mlua-0.3-1.rockspec"] = "92d00e0d52a7e187678de38b550ac8d0",
   tests = {
      ["createdb.sh"] = "06a113511efaa05cb7392932261e61e9",
      ["unittest.m"] = "1210aaecbeec8a8bc8afc9745129993d"
   }
}
```

I guess I want the Makefile wants add entries like:
```
   ['/usr/local/lib/lua/5.4/_yottadb.so'] = 'For removal by luarocks remove',
   ...
```
And then, of course, have `luarocks remove` actually remove those files.

Any thoughts would be appreciated.

Thanks,
Berwyn

**Comment by hishamhm** [comment]
Even though a Makefile can run arbitrary commands and therefore write anywhere in the filesystem, a Makefile used in LuaRocks _shouldn't_ be writing to arbitrary locations in your filesystem beyond the LuaRocks-managed prefixes. LuaRocks tries to never touch any paths other than its designated rocks-trees (e.g. `/usr/local/lib/lua/5.x`, `/usr/local/share/lua/5.x`, etc.). We do this to avoid clashing with the operating system's package manager.

When using the `make` backend, we recommend that one always passes to it make variables such as `PREFIX`, so that the `make` installation targets the LuaRocks-managed temporary build dir, which LuaRocks then uses to copy the files to their final rocks-tree locations. See https://github.com/luarocks/luarocks/wiki/Recommended-practices-for-Makefiles and
 https://github.com/luarocks/luarocks/wiki/Creating-a-Makefile-that-plays-nice-with-LuaRocks for more details.
 
 This behavior is unlikely to change, as LuaRocks does not intend to be come a general-purpose system-wide package manager for arbitrary files.

**Comment by berwynhoyt** [comment]
Thanks for the reply, @hishamhm. Given what you say, then what mechanism would you recommend for a user wanting to install mlua? Since mlua cannot be installed without creating a file in the yottadb directory (typically /usr/local/lib/yottadb, what should install that file? I understand that you don't want luarocks to interfere with the operating system's package manager, but I'm not sure how to resolve this problem. Are you saying that I shouldn't use luarocks to install mlua at all, and that the only correct way is for me to make an installer for apt/yum/homebrew/etc.?

**Comment by hishamhm** [comment]
@berwynhoyt I looked up your project, and it looks like it is a MUMPS plugin that embeds a Lua interpreter...

>  Are you saying that I shouldn't use luarocks to install mlua at all, 

...so yes, I'm afraid that's what I'm saying. LuaRocks is intended for Lua modules, that is, pieces of code you `require()` from Lua, and, as a stretch, pure-Lua applications where the application is essentially a Lua script + Lua modules that run on the system's Lua interpreter.

In that sense, your MLua project is more similar to things like [Love2D](https://love2d.org) (Lua engine over SDL), [OpenResty](https://www.opentresty.org) (Lua for Nginx), etc. None of these are installed _using_ LuaRocks, but once installed, Lua scripts running on them can make use of modules installed via LuaRocks.

Since your rockspec is currently using the `make` backend, LuaRocks really isn't bringing much to the table anyway. 

> and that the only correct way is for me to make an installer for apt/yum/homebrew/etc.?

If you wish do to so as a mean of growing the reach of your project, then yes, but projects often defer such downstream packaging to other contributors. It can be a lot of work. I have never personally maintained distro packages for LuaRocks or my other projects, but some of them were eventually picked up by distros. I think most of the time a Makefile with clear instructions, as you currently have, is sufficient. Maybe add something in your readme saying you'd accept contributions of downstream packaging?

**Comment by berwynhoyt** [comment]
Thanks for the perspective and suggestions, @hishamhm. You are right that MLua is a MUMPS plugin that embes Lua.

However, MLua has a sister-project, that I also maintain, called [lua-yottadb](https://github.com/anet-be/lua-yottadb) which offers complementary services in the opposite direction: it is a Lua module that provides MUMPS linkage. That sounds like something that you might consider appropriate as a luarocks module. However, it has the same problem -- that it needs to install a .so in /usr/local/lib/yottadb. What do you suggest for this lua module?
