### ISSUE TITLE
Versions 3.10 and above do not install properly on windows with certain lua installs

### ISSUE THREAD

**Issue by tobil4sk** [luarocks/luarocks#1700]
- **Platform:**
  - Windows. (mingw-msys)

- **LuaRocks version:**
  - 3.10.0 and above (any version that includes 1ed80a15d215f5b924008f61f4a30da6139ca1bf)

- **LuaRocks output from when the issue occurred:**
 
Relevant parts of the installation logs:

```
Interpreter found, now looking for link libraries...
    checking for D:\Dev\lua\lua_install\lua5.4.lib
    checking for D:\Dev\lua\lua_install\lua54.lib
    checking for D:\Dev\lua\lua_install\liblua54.a
    checking for D:\Dev\lua\lua_install\lua5.4.dll
    checking for D:\Dev\lua\lua_install\lua54.dll
    checking for D:\Dev\lua\lua_install\liblua.dll.a
    checking for D:\Dev\lua\lua_install\lib\lua5.4.lib
    checking for D:\Dev\lua\lua_install\lib\lua54.lib
    checking for D:\Dev\lua\lua_install\lib\liblua54.a
       Found liblua54.a
```
Then from `luarocks` we see:
```
      LUA_LIBDIR : D:\Dev\lua\lua_install\lib (not found)
```

```
Error: Failed finding Lua library. You may need to configure LUA_LIBDIR.
```

- **Description:**

I installed using hererocks:
```
hererocks lua_install -r@"v3.10.0" --lua=5.4 --verbose
```
Lua is installed like this:
```
bin\lua54.dll
lib\liblua54.a
```
Since `lib` is checked first and liblua54.a is found there, `lib` is what `LUA_LIBDIR` is set to. However, since this doesn't contain the `lua54.dll`, there is an error because the dll is not found in the configured `LUA_LIBDIR` path.

- **Possible solutions:**

Removing liblua*.a from here avoids the issue:
https://github.com/luarocks/luarocks/blob/f87568a7cba69e2c19411e7a2b73016c80a14a3b/install.bat#L342

Another solution would be to prioritise `bin` over `lib`.

Alternatively, perhaps hererocks should stop building liblua$LUA_SHORTV.a at all, because the mingw instructions say to install nothing to `lib`.

```
 To install Lua properly, open the top-level Makefile and change:
...
* cd src && $(INSTALL_DATA) $(TO_LIB) $(INSTALL_LIB) to #cd src && $(INSTALL_DATA) $(TO_LIB) $(INSTALL_LIB) 
```
https://lua-users.org/wiki/BuildingLua (see section on mingw-msys)

**Comment by tobil4sk** [comment]
Looks like the change was made in #1606. @hishamhm any insight on what the correct fix here would be? Should the install script be looking at `liblua$LUA_SHORTV.a` if it gets ignored later on when looking for the library to link against?

**Comment by hishamhm** [comment]
> Another solution would be to prioritise bin over lib.

Libraries in `bin` are very much a Windows-only thing, so I suppose prioritizing bin over lib would fix the issue in general without much consequence to other platforms. I suppose the order should change from `{ "lib", "", "bin" }` to `{ "", "bin", "lib" }`.

That's a backwards incompatible change, but I don't suppose there are installations out there with the correct library for the executable under `lib` and a wrong one under `bin`...

**Comment by tobil4sk** [comment]
> Libraries in bin are very much a Windows-only thing, so I suppose prioritizing bin over lib would fix the issue in general without much consequence to other platforms. I suppose the order should change from `{ "lib", "", "bin" }` to `{ "", "bin", "lib" }`.

Note, this is only relevant to the windows installer, so I don't think it should affect other platforms. Also, the current order seems to be `{ "", "lib", "bin" }`:
https://github.com/luarocks/luarocks/blame/f87568a7cba69e2c19411e7a2b73016c80a14a3b/install.bat#L347

I've opened: #1701

**Comment by hishamhm** [comment]
From LuaRocks 4 onwards (no ETA :( ), I hope to drop the `install.bat` installer and let `luarocks.exe` perform all its necessary detection at runtime.

We already have similar logic implemented that detects LUA_LIBDIR at runtime in case there is no config file that has already set it: (which is what `install.bat` currently does)

https://github.com/luarocks/luarocks/blob/master/src/luarocks/deps.lua#L769-L825

It uses the same search path priority for any external (C library) dependencies, which is set like this:

https://github.com/luarocks/luarocks/blob/master/src/luarocks/core/cfg.lua#L330-L331

My hope is to eventually move all logic that is currently in `install.bat` into LuaRocks itself, so that we can distribute a simple `luarocks.exe` on Windows that is smart enough so that can be used out-of-the-box (or at least smart enough that it can detect it is not yet fully-configured and ask the user to provide any missing settings).
