### ISSUE TITLE
luarocks show prints wrong directory

### ISSUE THREAD

**Issue by rrthomas** [luarocks/luarocks#424]
I installed a bunch of files whose name didn't end in `.lua` as Lua modules with `install.lua`. They are installed in the relevant `share` directory. But `luarocks show` prints out their paths under the corresponding `lib` directory, even though there are no files there.

For example: `lua = { ["foo.bar"] = "bar" }` in rockspec, file is installed under `share/5.3/package/bar`, but `luarocks show` says it's under `lib/5.3/package/bar`.

**Comment by mpeterv** [comment]
Should these files even be printed by `show`? E.g. sailor installs a lot of auxiliary files (javascript, various configs) and they are all shown, intermixed with real modules. Perhaps there should be a separate section for these installed files? It could handle executable scripts, too, which are currently not displayed in any way.

**Comment by mpeterv** [comment]
The problem is that Luarocks actually can't resolve module name to file path correctly using just the manifest. Manifest entries for each version map module names to paths relative to deployment dir for either Lua libs or C libs, but it doesn't say which. Luarocks currently guesses based on extension, and considers files with strange extensions C libs (in `path.which_i`), causing this issue.

(For same reason on `master` there is an issue with upgrading from a version providing a module as a Lua file to a version providing same module as a C lib: `manif.find_conflicting_file` assumes that old module should be deployed in the same directory as new one)

To fix this either manifest format should be extended (only possible in LR3?) or `path.which_i` should load rock manifest for package providing the module and use it directly.
