### ISSUE TITLE
How do i verify PGP signature for luarocks tarballs?

### ISSUE THREAD

**Issue by xpol** [luarocks/luarocks#643]
I have download both `luarocks-2.4.1.tar.gz` and `luarocks-2.4.1.tar.gz.asc` form http://keplerproject.github.io/luarocks/releases/
And running  `gpg --verify luarocks-2.4.1.tar.gz.asc` i got the follow message:

>gpg: assuming signed data in 'luarocks-2.4.1.tar.gz'
>gpg: Signature made Tue Nov  1 05:54:35 2016 CST using RSA key ID 2BB3C478
>gpg: Can't check signature: No public key

*I never used gpg before, and http://keplerproject.github.io/luarocks/releases/ does not proivde MD5...*

**Comment by hishamhm** [comment]
I uploaded my public key here:
http://pgp.mit.edu/pks/lookup?search=Hisham+Muhammad&op=vindex&fingerprint=on

**Comment by DemiMarie** [comment]
Note that MD5 is worthless – collisions in it are trivial to find.

**Comment by cxw42** [comment]
How I did it:

 1. I visited the [link](https://pgp.mit.edu/pks/lookup?search=Hisham+Muhammad&op=vindex&fingerprint=on) from @hishamhm
 1. I clicked on the 2016 "pub" link, since that is the most recent public key.  I got [the key file](https://pgp.mit.edu/pks/lookup?op=get&search=0x3FD8F43C2BB3C478).
 1. I saved they key file to disk as `h.html` (although I don't think the name or extension matter).
 1. I ran

        gpg --import h.html

    I got a "public key imported" message.
 1. I ran

        gpg --verify luarocks-2.4.2.tar.gz.asc luarocks-2.4.2.tar.gz

    That gave me a "Good signature" message.  I ignored the "not certified with a trusted signature" message, since removing that message involves paying a CA :) .

**Comment by hishamhm** [comment]
An update comment, since pgp.mit.edu doesn't seem to be up anymore:

My public key is available from my personal website, here: https://hisham.hm/public_key — the same steps as described above should still apply.
