### ISSUE TITLE
http://keplerproject.github.io/ URLs broken

### ISSUE THREAD

**Issue by Zash** [luarocks/luarocks#645]
https://keplerproject.github.io/luarocks/releases for example does not work currently

**Comment by Zash** [comment]
I suspected as much :) Does Github not have a way to do redirects for github.io sites?

http://luarocks.org/releases/ also redirects to the above keplerproject URL

**Comment by hishamhm** [comment]
@leafo can you take care of this redirect? I wasn't expecting keplerproject.github.io/luarocks to break in the move

**Comment by hishamhm** [comment]
(I mean luarocks.org/releases )

**Comment by leafo** [comment]
Can we render the contents of http://luarocks.github.io/luarocks/releases/ in the site? How are you rendering that page now?

**Comment by hishamhm** [comment]
it's handwritten HTML. It was a bare white page with links to tarballs
until last week. I'd just like to be able to upload a new release and get
it online quickly.

**Comment by leafo** [comment]
If you switch to creating a json file instead of HTML then I can consume it on webserver and render it into the regular layout

**Comment by hishamhm** [comment]
@leafo Does this look good? https://github.com/luarocks/luarocks/blob/gh-pages/releases/releases.json

This is intended as a replacement for both
http://luarocks.github.io/luarocks/releases/
and
https://github.com/luarocks/luarocks/wiki/Release-history

(I got rid of the release candidates in the JSON file because these have no release notes... should we keep them around?)

**Comment by daurnimator** [comment]
Have you considered just using the built-in github releases? https://github.com/luarocks/luarocks/releases

(by default it just has tags, you have to add release notes to turn a tag into a "release").

It is then consumable from https://api.github.com/repos/luarocks/luarocks/releases

**Comment by hishamhm** [comment]
I strongly dislike Github releases because you can't disable the often-broken tarballs they automatically generate. I know you can upload your own tarballs _in addition_ to the ones they create, but often you don't want a tarball release to be a snapshot of a git repo (e.g. when using Autotools) and I've had users download the wrong tarball many times because of this feature of Github for which sadly there is _no opt-out_.

**Comment by daurnimator** [comment]
> I strongly dislike Github releases because you can't disable the often-broken tarballs they automatically generate.

That is the snapshot system, which would be present with nearly all VCS guis.
I think your issue is more of an about the github GUI showing tags under releases then the functionality of getting a VCS snapshot tarball itself.

I was suggesting you use github releases + api as an alternative to manually maintaining a json file.

**Comment by hishamhm** [comment]
> I think your issue is more of an about the github GUI showing tags under releases then the functionality of getting a VCS snapshot tarball itself.

VCS snapshots are fine. As I said above, my problem is them showing up under "releases", and automatically and unavoidably presenting VCS snapshots of git tags for versions as if they are the tarballs for release versions.

> I was suggesting you use github releases + api as an alternative to manually maintaining a json file.

Yeah, I understood that. But maintaining that file would be less work than what I currently do. I do use Github Releases in other projects where I think it makes sense (ie, where I think its problems don't matter much), but I don't think it's a good fit for LuaRocks, because I've seen it cause confusion here already.

**Comment by hishamhm** [comment]
Ah, closing this one because the keplerproject.github.io URLs are no longer broken!

**Comment by Zash** [comment]
Thanks for fixing :)
