### ISSUE TITLE
luarocks the build-system

### ISSUE THREAD

**Issue by daurnimator** [luarocks/luarocks#671]
(This is something I've talked about before, but I can't find where we might have been tracking the discussion, please point me to it if you know)

The ability that luarocks provides for projects to specify how to build lua libraries in a common format is very valuable. For cooperating with my distro package manager, I'd like to be able to use luarocks *as* a build-tool, without the run-time package management component.

Practically, I think this might be as simple as adding a flag for `make`/`build`/`install` that indicates to *not* install the rockspec, manifest or other files into $tree/lib/luarocks (such as the copy of the `doc` directory).

**Comment by hishamhm** [comment]
Would it be feasible to run `luarocks` with  `--deps-mode=none --tree=$PWD/build` and then get the files you're interested in from `./build` and dispose of the rest?

I suppose it would be a good thing to fetch docs from there and include them with your package as well — sure, it's an extra copy but nothing too dramatic (and you could get docs from other rockspecs that use `make`, `cmake`, etc, from which you could not get the information via the rockspec alone).

Alternatively, I'd suggest you to _keep_ the `lib/luarocks` directory in your Arch-managed package and rebuild the manifest in the "post-install" stage of your package, so that Arch-installed rocks show up in `luarocks list`. We could add a "locked" flag to a local repo so that the `luarocks` command-line tool could not add/remove to the system-managed directory (but rocks installed into other places such as `~/.luarocks` could be able to use system-installed rocks as dependencies).

**Comment by daurnimator** [comment]
> Would it be feasible to run luarocks with --deps-mode=none --tree=$PWD/build and then get the files you're interested in from ./build and dispose of the rest?

I'd much prefer a flag to `make`/`install` to skip the manifest generation step.

> Alternatively, I'd suggest you to keep the lib/luarocks directory in your Arch-managed package and rebuild the manifest in the "post-install" stage of your package, so that Arch-installed rocks show up in luarocks list.

I looked into this approach: the conclusion is that people didn't want to have luarocks as a run-time dependency.

The other aspect is that luarocks should check for rocks missing from manifest on installation or similar.  (to pick up existing lua packages)

**Comment by hishamhm** [comment]
Would installing the lib/luarocks files be acceptable, even without running
the post-install manifest generation step? (somewhat like installing .pc
files for a C library) This way we could at least check, otherwise LuaRocks
can't detect a dependency out of a raw, unversioned .lua or .so file.

**Comment by daurnimator** [comment]
I think installing the per-package manifest would be okay. Just not the top level one.

**Comment by daurnimator** [comment]
I think this was fixed with #1102
