### ISSUE TITLE
"Unknown number type, check LUA_NUMBER_* in luaconf.h"

### ISSUE THREAD

**Issue by sukidesuaoi** [luarocks/luarocks#765]
Hi,

I am currently trying out lua in kong, however when I trigger "luarocks make" I am encountering this error:

Installing https://luarocks.org/luabitop-1.0.2-1.src.rock
gcc -O2 -fPIC -I/usr/local/include -c bit.c -o bit.o
bit.c: In function ‘barg’:
bit.c:83:2: error: #error "Unknown number type, check LUA_NUMBER_* in luaconf.h"
 #error "Unknown number type, check LUA_NUMBER_* in luaconf.h"

I'm fairly new to lua and unfamiliar with the error message. Can anybody help me?
 I'm running this in Oracle linux

Thank you in advance.

**Comment by hishamhm** [comment]
This sounds like a mixup between Lua header and library versions. Do you
happen to have more than one copy of lua.h in your system?

**Comment by sukidesuaoi** [comment]
Hi @hishamhm thank you, I only have 1 lua.h in the system. 

I have tried to read the bit.c and the luaconf.h, I'm not sure if it is a proper solution for this, but I added a 

#define LUA_NUMBER_DOUBLE

and it finally compiled. I think it is looking for a define for LUA_NUMBER_*. Although I am not sure about this. 

I am having so much trouble installing the lua and luarocks in oracle linux. -_-

**Comment by max1220** [comment]
The relevant peaces of code from bit.c are the following:
```
#if defined(LUA_NUMBER_DOUBLE)
    (...)
#elif defined(LUA_NUMBER_INT) || defined(LUA_NUMBER_LONG) || \
    defined(LUA_NUMBER_LONGLONG) || defined(LUA_NUMBER_LONG_LONG) || \
    defined(LUA_NUMBER_LLONG)
    (...)
#elif defined(LUA_NUMBER_FLOAT)
    #error "A 'float' lua_Number type is incompatible with this library"
#else
    #error "Unknown number type, check LUA_NUMBER_* in luaconf.h"
#endif
```
This error occurring probably means that the preprocessor didn't process luaconf.h properly, luaconf.h is misconfigured, or you're trying to compile this under Lua 5.3.

**Comment by hishamhm** [comment]
@sukidesuaoi Are you following the Kong instructions? https://getkong.org/install/source/ (They include the installation of OpenResty, which bundles LuaJIT, and LuaRocks). From the sound of it, you have a different version of Lua installed and that is causing conflicts with the OpenResty/Kong stuff. Better to uninstall Lua/LuaRocks from your system and try from scratch following the Kong instructions.

Closing this for now since it's more of a support issue than a bug, but feel free to reply if you have further questions.
