### ISSUE TITLE
flaw in finding dependencies for builtin plugins.

### ISSUE THREAD

**Issue by teto** [luarocks/luarocks#766]
Trying to install luaevent on nixos via luarocks, I found a bug in the dependency search system (on master).

In the luaevent rockspec we have
```
external_dependencies = {
   EVENT = {
      header = "event.h",
      library = "event",
   }
}
```
In my case, the files are in /nix/store/ilrnw3142kgcqsgdc04b9jvsw63rgv3i-libevent-2.1.8-dev/include/event.h and /nix/store/zlc0fglvm6836npm3gagsyw8jpbvf7xw-libevent-2.1.8/lib/libevent.so.
The used rockspec config is
```
external_deps_dirs = {
"/nix/store/zlc0fglvm6836npm3gagsyw8jpbvf7xw-libevent-2.1.8",
"/nix/store/ilrnw3142kgcqsgdc04b9jvsw63rgv3i-libevent-2.1.8-dev"
}
```
Luarocks first start trying to find event.h in /nix/store/zlc0fglvm6836npm3gagsyw8jpbvf7xw-libevent-2.1.8.
as it can't find it, it hits this `break` 
https://github.com/luarocks/luarocks/blob/4c22bfb86abcd97253c73d2175d0a715c2a2cc12/src/luarocks/deps.lua#L354
which exit the loops 
https://github.com/luarocks/luarocks/blob/4c22bfb86abcd97253c73d2175d0a715c2a2cc12/src/luarocks/deps.lua#L286
This loop iterates over the subdirs BINDIR/INCDIR/LIBDIR which means /nix/store/zlc0fglvm6836npm3gagsyw8jpbvf7xw-libevent-2.1.8/lib is never explored, thus libevent.so is never found.
If I remove the `break`,  luarocks manages to find both the library and header files but still complains about unncessary other missing files (libevent.a but it found libevent.so !). I am not sure how to fix this properly, the logic is hard, it might be worth to log  some operations to help debug (I myself added print all over the place).

**Comment by hishamhm** [comment]
Without looking at the code (I'm typing this from my phone), the problem seems to be that the two files live in different prefixes, which is a use-case I have never encountered before. (In non-Nix systems, trying to use headers from, say, /usr and libraries from /usr/local is a recipe for disaster – GoboLinux, which does per-program directories as well, avoids this problem because there are no -dev packages: one upstream tarball produces one /Programs entry)

Allowing this in general sounds a bit risky for general users. 

Instead of adding these two entries to `external_deps_dirs`, how about setting `variables.EVENT_INCDIR` and `variables. EVENT_LIBDIR` instead? Would that be a workable solution?

**Comment by teto** [comment]
Hum I see your point (as luarocks defaults to /usr/ , /usr/local for external deps, it could indeed be a problem).
Setting EVENT_INCDIR / EVENT_LIBDIR should work I will try that thanks.

**Comment by teto** [comment]
A posteriori, converting `builtin` luarocks module with external dependencies to nix packages looks too brittle (first you need to map the package name from luarocks one to the nix one, "nix-locate" can help but still unreliable ) so for now I will disable it, builtin packages with external dependencies have to be written manually for now.

Thanks for the help.
