### ISSUE TITLE
Move license info into a LICENSE file please

### ISSUE THREAD

**Issue by coopr** [luarocks/luarocks#829]
and thanks!

**Comment by hishamhm** [comment]
@coopr `COPYING`, which we use, is an industry-standard name for license files as well. Thousands of open source projects use it.

**Comment by coopr** [comment]
I opened this because I thought that the lack of a LICENSE file at the root level of the repo means that there is no clear display on the repo, at least in Github, of the license that applies (here https://github.com/Kong/kong/blob/master/LICENSE is an example of a repo where Github has detected the LICENSE file and license type) 

Now that I've read COPYING a little more carefully, I think I see why - I believe it is because LuaRocks is licensed under "non-standard" terms that GitHub cannot parse and reduce to "MIT" or Apache" etc - is that right?

**Comment by hishamhm** [comment]
@coopr they are not non-standard terms, it's a <a href="https://opensource.org/licenses/MIT">regular MIT License</a>. The other `COPYING.*` files are only there for files that are installed in the all-in-one Windows bundle of LuaRocks, and do not apply to Unix (Linux/macOS/etc) installations.

I don't know why Github fails to detect the license, maybe it's because this repo wasn't created in Github (btw, LuaRocks predates it :) ) — for new Github repos you get a license dropdown when the repo is created, so maybe Github gets its info that rather than parsing the license. When this repo was imported into Github this feature didn't exist.

**Comment by coopr** [comment]
Could we go belt and suspendere, and I'll PR addition of an MIT license? Or do you prefer that we leave it as is?

**Comment by hishamhm** [comment]
The COPYING file _is_ the license file. Even Github recognizes it as such: https://github.com/luarocks/luarocks/community

**Comment by hishamhm** [comment]
Oops, that link is visible only to project members, I think. In any case, it looks the same as https://github.com/kong/kong/community and in the case of LuaRocks the "License" link automatically points to https://github.com/luarocks/luarocks/blob/master/COPYING — there's no action needed, here. LuaRocks is properly MIT-licensed.

**Comment by siffiejoe** [comment]
I found the [GitHub documentation about license detection][1]. They use a ruby gem called `licensee` to detect a license for a repository. Here is what `licensee` has to say about the luarocks repo:

```
License:        NOASSERTION
Matched files:  COPYING, COPYING_7z, COPYING_lua, COPYING_win
COPYING:
  Content hash:  46cdc03462b9af57968df67b450cc4372ac41f53
  Attribution:   Copyright 2007-2014 Kepler Project.
  Confidence:    100.00%
  Matcher:       Licensee::Matchers::Exact
  License:       MIT
COPYING_7z:
  Content hash:  c07dcc453865aa50383fa2ba20bb411f6bcb8cc6
  License:       NOASSERTION
  Closest licenses:
    Unlicense similarity:  38.10%
    Zlib similarity:       36.11%
    MS-PL similarity:      35.05%
COPYING_lua:
  Content hash:  b84743f44c48f1eb12d8380778e6408638785e16
  License:       NOASSERTION
  Closest licenses:
    MIT similarity:      85.05%
    UPL-1.0 similarity:  62.96%
    BSL-1.0 similarity:  61.54%
COPYING_win:
  Content hash:  7187d1fed9f5f79980665c1ed21d0b0ba765b788
  License:       NOASSERTION
  Closest licenses:
    BSL-1.0 similarity:  13.48%
    WTFPL similarity:    13.46%
    MS-PL similarity:    12.90%
```

Note the `License: NOASSERTION` on the first line. If I remove the extra `COPYING_*` files, the output becomes:

```
License:        MIT
Matched files:  COPYING
COPYING:
  Content hash:  46cdc03462b9af57968df67b450cc4372ac41f53
  Attribution:   Copyright 2007-2014 Kepler Project.
  Confidence:    100.00%
  Matcher:       Licensee::Matchers::Exact
  License:       MIT
```

So the problem seems to be that `licensee` gets confused by the extra `COPYING_*` files, **not** the file name (`COPYING`) of the main license file.

Whether we want to do something about the situation is another story ...
Maybe we should update the copyright date, though.

  [1]:  https://help.github.com/articles/licensing-a-repository/#detecting-a-license

**Comment by hishamhm** [comment]
@siffiejoe Thanks for the research! I'll move the other files to `win32` to make our root dir cleaner, Github happier and things less confusing, and update the copyright date.
