### ISSUE TITLE
Use `command -v` instead of `wget --version` on *nix systems?

### ISSUE THREAD

**Issue by helpermethod** [luarocks/luarocks#902]
It seems `wget --version` is used to check if the `wget` executable exists:

    os.execute: 	cd '/' && 'wget' '--version'

The problem with this approach is that not all versions of `wget` seem to support that flag.

E.g. Alpine 3.8 has a version of `wget`without the `--version`flag.

So for such systems a check like

    os.execute: 	cd '/' && 'command' '-v' 'wget'

would work.

**Comment by hishamhm** [comment]
If Alpine's wget doesn't have --version, it probably doesn't have the other flags we assume are available (I guess it's the busybox version, which is a wget-workalike with limited functionality?)

I'm reluctant on changing this, because we don't use the Busybox version in our test matrix, so when we test for wget, we're really expecting GNU Wget.

**Comment by helpermethod** [comment]
Hi, it's actually possible to install the GNU version of `wget` which should fix the problem. Like you said it's probably not worth it to change the check for non-GNU versions of `wget`. Closing the ticket for now.
