### ISSUE TITLE
Custom build back-ends extending the 'builtin' build.type (e.g. for C++)

### ISSUE THREAD

**Issue by osch** [luarocks/luarocks#914]
Hi, I'm interested in custom build-backends for more complex build features but similar to the builtin back-end. Extended build features could be: supporting C++ and using commands for finding out compile & link options (e.g. trying `pkg-config` on Unix based systems).

See for example [luarocks-build-cpp](https://luarocks.org/modules/luarocks/luarocks-build-cpp). This is a fork of the builtin back-end with basic C++ support.

The advantage of externally supplied build back-ends is preserving backwards-compatibility to older luarocks versions while providing extended build mechanisms that can access luarocks features (e.g. configuration/variables). As shown in luarocks-build-cpp the extended build-backend can be supplied over luarocks and can use all luarocks modules that are not based on the extended back-end.

The disadvantage of externally supplied build back-ends is that they may break if luarocks changes too much. E.g. luarocks-build-cpp is broken for luarocks 3.0.x because `luarocks.cfg` was moved to `luarocks.core.cfg`. I fixed this issue and created automatic Travis &  Appveyor tests for Linux, Windows & MacOS, see https://github.com/osch/luarocks-build-cpp.

So what do you think about this? I think it could be worth to develop a custom build-backend and to adjust it for changes in luarocks from time to time, but: Are there big changes on the way that could break custom build back-ends completely? At least [luarocks-build-cpp](https://luarocks.org/modules/luarocks/luarocks-build-cpp) was uploaded by the user *luarocks* to luarocks.org so this suggests that there is some awareness of the existence of custom build-backends ;-)
Best regards, Oliver

**Comment by hishamhm** [comment]
Hi,

The "luarocks" account contains all rocks that were converted from the original luarocks.org server and haven't been claimed by their authors. Since the repo of that project hasn't been updated since 2013 and you made maintenance updates to it in your fork, if you'd like I could transfer the `luarocks-build-cpp` name in the root manifest over to you, so you could upload an updated rockspec.

Yes, custom build backends were always meant to be supported. Support for them has improved in LuaRocks 3.0, because you can now use the `build_dependencies=()` table to specify them (and therefore not load them when using binary rocks with `luarocks install` — they become a dependency only for rockspecs and src.rock files).

You bring a good point about LuaRocks version compatibility. The contract for a backend is to live in `luarocks.build.*` and provide a `run(rockspec)` function which produces files in `path.lua_dir(rockspec.name, rockspec.version)` and/or `path.lib_dir(rockspec.name, rockspec.version)` and returns `true` or `nil, string`. That much hasn't changed. But as you point out, other internals such as `luarocks.core.cfg` have, and there's no guarantee on the stability of the internals. It's hard to draw a line here because each backend can load arbitrary modules: builtin loads fs, path, util, cfg, dir; cmake only loads fs; util, cfg.

So, to answer your question:

> Are there big changes on the way that could break custom build back-ends completely? 

No, none are currently planned. But it's interesting to think how build and test backends could protect themselves from internal changes. We _are_ working on introducing a public API for LuaRocks clients (in the `luarocks-api` branch), so I wonder if the functionality needed by build backends should be provided by this (stable, versioned) API as well.

**Comment by hishamhm** [comment]
Closing this as I think it's been answered, but feel free to comment!

**Comment by osch** [comment]
Thank you for your detailed answer.

> if you'd like I could transfer the luarocks-build-cpp name in the root manifest over to you, so you could upload an updated rockspec.

Yes, that whould be fine, I will then upload an updated rockspec.

> Yes, custom build backends were always meant to be supported. Support for them has improved in LuaRocks 3.0

That's good to hear so now I'm encouraged to work further on this topic :-) But for now I have ambitions to make it also work for LuaRocks 2.4., so I will try to implement fallback solutions if I'm using some LuaRocks 3.0 specific extensions that are not available in 2.4.
Best regards, Oliver
