### ISSUE TITLE
`luarocks install version` fails

### ISSUE THREAD

**Issue by hishamhm** [luarocks/luarocks#954]
probably getting confused with `version.lua` as a directory name

**Comment by Tieske** [comment]
Can simply be reproduced: `luarocks install version 1.0.1-1` (a new rockspec `1.0.1-2` has been uploaded that actually works, so the faulty one stays around for troubleshooting purposes)

The rock was build using `luarocks upload`, when inspecting the generated rock, the file inside the rock is called `version.lua` instead of `src/version.lua`. So my guess is that the command to pack the rock is the culprit in this case.

**Comment by gszr** [comment]
It looks like this one is already fixed?
```
$ luarocks install version 1.0.1-1              
Installing https://luarocks.org/version-1.0.1-1.src.rock

version 1.0.1-1 depends on lua >= 5.1 (5.1-1 provided by VM: success)
version 1.0.1-1 is now installed in /Users/gs@konghq.com/Code/kong/bazel-bin/build/kong-dev (license: Apache 2.0)

```

LuaRocks 3.11.1
