### ISSUE TITLE
stop storing binaries in version control

### ISSUE THREAD

**Issue by ghost** [luarocks/luarocks#960]
i see the executable files are stored in version control here

https://github.com/luarocks/luarocks/tree/gh-pages

there really is no point of putting these in version control, as you can just create releases with attached binaries here

https://github.com/luarocks/luarocks/releases

**Comment by SlySven** [comment]
Might be that https://help.github.com/en/github/managing-large-files/what-is-my-disk-quota#packaged-release-versions is relevant here... 😉

**Comment by hishamhm** [comment]
> there really is no point of putting these in version control

for one, it's easier to move them out of GitHub if the need for that ever comes (just like we've had to unexpectedly migrate away from SourceForge back in the day... you never know)

**Comment by alerque** [comment]
Keeping an archive of those for the web site does make some sense, but it also makes the main `luarocks` repository pretty heavy to clone for what it is. Since that's a separate branch with an independent root, it might make sense to split the luarocks GH Pages site off into a separate repo with the exact history it has (no rewriting required) so the branch could be dropped here. That would make the repo a quite normal weight to clone for a what is mostly a bit of Lua code.

**Comment by hishamhm** [comment]
I personally have no interest in spending the required amount of time it would take to rework all of that (moving things around, setting up repos, fixing release scripts) in exchange for a few seconds of `git clone` time.
